import Navbar from '@/components/Navbar'
import { Inter } from 'next/font/google'
import './globals.css'
// import connectMongo from '@/dbConnect/connectMongo'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'KhanaKhazana',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  // await connectMongo()
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  )
}
