import Navbar from '@/components/Navbar'
import { Inter } from 'next/font/google'
import './globals.css'
import AuthProvider from './provider/AuthProvider'
import { Toaster } from 'sonner'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "KhanaKhazana",
  description: "Generated by create next app",
  openGraph: {
    images: [
      {
        url: "http://localhost:3000/api/og",
        width: 1200,
        height: 600,
      },
    ],
  },
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />
          <main>{children}</main>
          <div id="modal-root-content" />
        </AuthProvider>
        <Toaster position='top-right' toastOptions={{
          style: {backgroundColor: 'green'},
          className:'sonner-text'
        }} />
      </body>
    </html>
  )
}
