import Hero from '@/components/Hero'
import RecipeCard from '@/components/recipes/RecipeCard'
import Sidebar from '@/components/recipes/Sidebar'
import { getAllRecipes } from '@/db/queries'

export const metadata = {
  title: 'Khana Khazana - Home',
  description: 'Generated by create next app',
  openGraph: {
    images: [
      {
        url: 'https://m-khana-khazana.vercel.app/api/og',
        width: 1200,
        height: 600,
      },
    ],
  },
}

export default async function Home() {
  const allRecipes = await getAllRecipes()
  return (
    <div className="container">
      <Hero />
      <section className=" py-8">
        <div className="grid grid-cols-12 py-4">
          <Sidebar />
          <div className="col-span-12 md:col-span-9">
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 my-8 justify-items-center">
              {allRecipes?.length > 0 ? (
                allRecipes.map((recipe) => (
                  <RecipeCard key={recipe?.id} recipe={recipe} />
                ))
              ) : (
                <li className="text-xl text-center mt-5">No recipes found!</li>
              )}
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
